### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by zhang2333-Myself** [Apricityx/koishi-plugin-NLR-meme#1]
插件加载失败，这可能是插件本身的问题所致。请联系插件作者并反馈此问题。
![image](https://github.com/user-attachments/assets/ab9d90dd-136c-4bae-92f9-cbd5f8aa5cd7)

日志：
2024-08-02 13:15:33 [I] loader apply plugin nlr-meme:vn9hc2
2024-08-02 13:15:33 [E] loader Error: Cannot find module '@satorijs/element/jsx-runtime'
                        Require stack:
                        - /home/user/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js
                        - /home/user/3/koishi-app/node_modules/@koishijs/loader/lib/index.js
                        - /home/user/3/koishi-app/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
                            at Module._load (node:internal/modules/cjs/loader:975:27)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
                            at require (node:internal/modules/helpers:177:18)
                            at Object.<anonymous> (/home/user/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js:4:23)
                            at Module._compile (node:internal/modules/cjs/loader:1356:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
                            at Module.load (node:internal/modules/cjs/loader:1197:32)
                            at Module._load (node:internal/modules/cjs/loader:1013:12)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)

**Comment by zhang2333-Myself** [comment]
还有好奇一下这个得到作者许可了吗

**Comment by zhang2333-Myself** [comment]
![image](https://github.com/user-attachments/assets/ffa65bf0-aea7-4c2f-a3e7-c9159a2f7276)
现在好像什么接口也没正式公开啊

**Comment by Apricityx** [comment]
我和作者私下聊过，没有反对意见，我这边能正常使用，可以尝试重新安装此插件，如仍旧无法使用，请附上完整错误日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 中午1:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1)




 
image.png (view on web)
 现在好像什么接口也没正式公开啊

**Comment by zhang2333-Myself** [comment]
日志·：
2024-08-02 18:46:14 [I] app Koishi/4.17.10
2024-08-02 18:46:15 [I] loader apply plugin group:entry
2024-08-02 18:46:15 [I] loader apply plugin group:server
2024-08-02 18:46:15 [I] loader apply plugin server:63f84c
2024-08-02 18:46:15 [I] loader apply plugin group:basic
2024-08-02 18:46:15 [I] loader apply plugin admin:gssv1j
2024-08-02 18:46:15 [I] loader apply plugin commands:jrnzx4
2024-08-02 18:46:15 [I] loader apply plugin help:atenp3
2024-08-02 18:46:15 [I] loader apply plugin http:jbru36
2024-08-02 18:46:15 [I] loader apply plugin locales:5h6efp
2024-08-02 18:46:15 [I] loader apply plugin proxy-agent:uzfci2
2024-08-02 18:46:15 [I] loader apply plugin rate-limit:e0pvvq
2024-08-02 18:46:15 [I] loader apply plugin telemetry:qo0y3k
2024-08-02 18:46:15 [I] loader apply plugin group:console
2024-08-02 18:46:15 [I] loader apply plugin actions:z1fswt
2024-08-02 18:46:15 [I] loader apply plugin analytics:05nnx9
2024-08-02 18:46:15 [I] loader apply plugin config:soakvc
2024-08-02 18:46:16 [I] loader apply plugin console:o2ger7
2024-08-02 18:46:16 [I] loader apply plugin dataview:0gbyr2
2024-08-02 18:46:16 [I] loader apply plugin explorer:w7fkie
2024-08-02 18:46:16 [I] loader apply plugin logger:exia8s
2024-08-02 18:46:16 [I] loader apply plugin insight:zwcu5u
2024-08-02 18:46:16 [I] loader apply plugin market:ur0zu3
2024-08-02 18:46:16 [I] loader apply plugin notifier:kf2h0f
2024-08-02 18:46:16 [I] loader apply plugin oobe:n3oo32
2024-08-02 18:46:16 [I] loader apply plugin sandbox:bylgaf
2024-08-02 18:46:16 [I] loader apply plugin status:tmyj8d
2024-08-02 18:46:16 [I] loader apply plugin theme-vanilla:h723w6
2024-08-02 18:46:16 [I] loader apply plugin group:storage
2024-08-02 18:46:16 [I] loader apply plugin database-sqlite:eqk9lu
2024-08-02 18:46:16 [I] loader apply plugin assets-local:061sbs
2024-08-02 18:46:16 [I] loader apply plugin group:adapter
2024-08-02 18:46:16 [I] loader apply plugin adapter-qq:67ef92
2024-08-02 18:46:16 [I] loader apply plugin echo:l5o85n
2024-08-02 18:46:16 [I] loader apply plugin ffmpeg:h69ona
2024-08-02 18:46:16 [I] loader apply plugin downloads:g8dwas
2024-08-02 18:46:16 [I] loader apply plugin checkin:d7pnjo
2024-08-02 18:46:16 [I] loader apply plugin monetary:vv5j61
2024-08-02 18:46:16 [I] loader apply plugin text-censor:wfus71
2024-08-02 18:46:16 [I] loader apply plugin group-manage:x1jm5k
2024-08-02 18:46:17 [I] assets missing config "selfUrl", fallback to "file:" scheme
2024-08-02 18:46:17 [E] app RangeError: Maximum call stack size exceeded
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:63:43)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
                            at Tree.insertNode (/home/Zpcin/3/koishi-app/node_modules/mint-filter/dist/core/tree.js:73:18)
2024-08-02 18:46:17 [I] server server listening at http://0.0.0.0:5140
2024-08-02 18:46:17 [I] console webui is available at http://127.0.0.1:5140
2024-08-02 18:46:17 [W] app Error: Cannot find module '@satorijs/element/jsx-runtime'
                        Require stack:
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/client/id.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/client/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/plugins/storage.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/plugins/basis.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/plugins/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/@koishijs/loader/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
                            at Module._load (node:internal/modules/cjs/loader:975:27)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
                            at require (node:internal/modules/helpers:177:18)
                            at Object.<anonymous> (/home/Zpcin/3/koishi-app/node_modules/koishi-plugin-telemetry/lib/client/id.js:5:23)
                            at Module._compile (node:internal/modules/cjs/loader:1356:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
                            at Module.load (node:internal/modules/cjs/loader:1197:32)
                            at Module._load (node:internal/modules/cjs/loader:1013:12)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-08-02 18:46:20 [I] adapter connect to server: wss://api.sgroup.qq.com/websocket
2024-08-02 18:46:32 [W] config failed to load nlr-meme
2024-08-02 18:46:32 [W] config Error: Cannot find module '@satorijs/element/jsx-runtime'
                        Require stack:
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/@koishijs/loader/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
                            at Module._load (node:internal/modules/cjs/loader:975:27)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
                            at require (node:internal/modules/helpers:177:18)
                            at Object.<anonymous> (/home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js:4:23)
                            at Module._compile (node:internal/modules/cjs/loader:1356:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
                            at Module.load (node:internal/modules/cjs/loader:1197:32)
                            at Module._load (node:internal/modules/cjs/loader:1013:12)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-08-02 18:48:03 [I] loader apply plugin nlr-meme:ohpx3f
2024-08-02 18:48:03 [E] loader Error: Cannot find module '@satorijs/element/jsx-runtime'
                        Require stack:
                        - /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/@koishijs/loader/lib/index.js
                        - /home/Zpcin/3/koishi-app/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
                            at Module._load (node:internal/modules/cjs/loader:975:27)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)
                            at require (node:internal/modules/helpers:177:18)
                            at Object.<anonymous> (/home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme/lib/index.js:4:23)
                            at Module._compile (node:internal/modules/cjs/loader:1356:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
                            at Module.load (node:internal/modules/cjs/loader:1197:32)
                            at Module._load (node:internal/modules/cjs/loader:1013:12)
                            at Module.require (node:internal/modules/cjs/loader:1225:19)

**Comment by zhang2333-Myself** [comment]
2024-08-02 19:40:23 [W] market npm WARN ERESOLVE overriding peer dependency
2024-08-02 19:40:23 [W] market npm WARN While resolving: koishi-app@0.0.0
2024-08-02 19:40:23 [W] market npm WARN Found: @satorijs/element@1.1.3
2024-08-02 19:40:23 [W] market npm WARN node_modules/@satorijs/element
2024-08-02 19:40:23 [W] market npm WARN   @satorijs/element@"3.1.7" from the root project
2024-08-02 19:40:23 [W] market npm WARN   1 more (koishi-plugin-bella-sign-in)
2024-08-02 19:40:23 [W] market npm WARN 
2024-08-02 19:40:23 [W] market npm WARN Could not resolve dependency:
2024-08-02 19:40:23 [W] market npm WARN peer @satorijs/element@"^1.0.0" from koishi-plugin-bella-sign-in@2.0.4
2024-08-02 19:40:23 [W] market npm WARN node_modules/koishi-plugin-bella-sign-in
2024-08-02 19:40:23 [W] market npm WARN   koishi-plugin-bella-sign-in@"2.0.4" from the root project
2024-08-02 19:40:24 [W] market npm ERR! code ENOTEMPTY
2024-08-02 19:40:24 [W] market npm ERR! syscall rename
2024-08-02 19:40:24 [W] market npm ERR! path /home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme
2024-08-02 19:40:24 [W] market npm ERR! dest /home/Zpcin/3/koishi-app/node_modules/.koishi-plugin-nlr-meme-gbcVbj1k
2024-08-02 19:40:24 [W] market npm ERR! errno -39
2024-08-02 19:40:24 [W] market npm ERR! ENOTEMPTY: directory not empty, rename '/home/Zpcin/3/koishi-app/node_modules/koishi-plugin-nlr-meme' -> '/home/Zpcin/3/koishi-app/node_modules/.koishi-plugin-nlr-meme-gbcVbj1k'
2024-08-02 19:40:24 [W] market 
2024-08-02 19:40:24 [W] market npm ERR! A complete log of this run can be found in:
2024-08-02 19:40:24 [W] market npm ERR!     /root/.npm/_logs/2024-08-02T11_40_18_218Z-debug-0.log

**Comment by zhang2333-Myself** [comment]
重装koishi已解决

**Comment by zhang2333-Myself** [comment]
你好，这个问题解决了，沙盒里一直是一个图，qq没有反应，我不知道是不是自己的问题，不知道怎么解决，请教一下（）











---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 中午1:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1)




 我和作者私下聊过，没有反对意见，我这边能正常使用，可以尝试重新安装此插件，如仍旧无法使用，请附上完整错误日志 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年8月2日(周五) 中午1:27 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1) 
 
 
 
 
   
 image.png (view on web) 
  现在好像什么接口也没正式公开啊

**Comment by zhang2333-Myself** [comment]
2024-08-02 20:25:45 [W] session Error: Bad Request
                            at [cordis.invoke] (/home/Zpcin/3/1/node_modules/@cordisjs/plugin-http/lib/index.cjs:332:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async <computed> [as sendFileGuild] (/home/Zpcin/3/1/node_modules/@satorijs/adapter-qq/lib/index.cjs:587:32)
                            at async QQMessageEncoder.sendFile (/home/Zpcin/3/1/node_modules/@satorijs/adapter-qq/lib/index.cjs:1067:15)
                            at async QQMessageEncoder.visit (/home/Zpcin/3/1/node_modules/@satorijs/adapter-qq/lib/index.cjs:1126:20)
                            at async QQMessageEncoder.render (/home/Zpcin/3/1/node_modules/@satorijs/core/lib/index.cjs:586:7)
                            at async QQMessageEncoder.visit (/home/Zpcin/3/1/node_modules/@satorijs/adapter-qq/lib/index.cjs:1179:7)
                            at async QQMessageEncoder.render (/home/Zpcin/3/1/node_modules/@satorijs/core/lib/index.cjs:586:7)
                            at async QQMessageEncoder.visit (/home/Zpcin/3/1/node_modules/@satorijs/adapter-qq/lib/index.cjs:1179:7)
                            at async QQMessageEncoder.render (/home/Zpcin/3/1/node_modules/@satorijs/core/lib/index.cjs:586:7)

**Comment by Apricityx** [comment]
沙盒里一直是一个图是沙盒的特性，我在qq群是没问题的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1)




 你好，这个问题解决了，沙盒里一直是一个图，qq没有反应，我不知道是不是自己的问题，不知道怎么解决，请教一下（） 
 
 
 
 
 
 
 
 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年8月2日(周五) 中午1:38 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1) 
 
 
 
 
  我和作者私下聊过，没有反对意见，我这边能正常使用，可以尝试重新安装此插件，如仍旧无法使用，请附上完整错误日志  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2024年8月2日(周五) 中午1:27  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: Re: [Apricityx/koishi-plugin-NLR-meme] 插件加载失败 (Issue #1)  
   
   
   
   
     
  image.png (view on web)  
   现在好像什么接口也没正式公开啊
